version: '3'

services:
  db-service:
    image: public.ecr.aws/bitnami/postgresql:13.7.0
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    hostname: db-service

volumes:
  pg-data:
    external: true
